version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: ~/mouse-posyx
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt install cmake zlib1g-dev libx11-dev libxtst-dev libssl-dev
      - run:
          name: Initialize Git Submodule
          command: |
            git submodule init
            git submodule update
      - run:
          name: Install libwebsockets
          command: |
            cd libwebsockets
            mkdir build
            cd build
            cmake ..
            make
            sudo make install
            cd ~/mouse-posyx
      - run:
          name: Build mouse-posyx
          command: |
            mkdir build
            cd build
            cmake ..
            make
workflows:
 version: 2
 build_commits:
   jobs:
     - build
